### ISSUE TITLE
Validation of 'default' and 'enum' values against associated schemas

### ISSUE THREAD

**Issue by IvanGoncharov** [zaggino/z-schema#110]
According to [Draft4](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2.2)
> It is RECOMMENDED that a default value be valid against the associated schema.
As for `enum` there is no such recommendation, but I plan to submit PR.

Right know library consider following a valid schema:
```json
{
  "type": "string",
  "enum": [1,2,3],
  "default": true
}
```

It would be very useful to implement such check and enable it by special flag.

**Comment by IvanGoncharov** [comment]
@zaggino, I reviewed you code and have solution.
I will try to submit in next couple of days.
Can you suggest name for flag which will enable such validation?

**Comment by zaggino** [comment]
this is now published in `3.11.0`

**Comment by whitlockjc** [comment]
Two quick items:

* This should be documented *(A simple PR of course)*
* Why wasn't this applied to `JsonValidation` as well?  In swagger-tools I currently have to manually validate all `default` values against their respective JSON Schema but I'd love to not have to do this if possible.

**Comment by IvanGoncharov** [comment]
> Why wasn't this applied to JsonValidation as well?

@whitlockjc How it could be applied to `JsonValidation`? It's validation of JSON Schema field `default`.

> In swagger-tools I currently have to manually validate all default values against their respective JSON Schema

Funny enough, it was my original intention.
In `swagger-tools` you don't validate `default` value of method parameters.
You can fix that by putting entire parameter through Schema validation.
And for Schema objects you should do the same.

**Comment by whitlockjc** [comment]
Yeah, after digging I see that there is no good way to do this in z-schema unless I'm missing something.  I was aware that with non-body parameters that this would be a pain since the parameter definition is not a JSON Schema like a body parameter is.

As for swagger-tools not validating default values of method parameters, it really does.  *(https://github.com/apigee-127/swagger-tools/blob/master/lib/validators.js#L527)*  I'm sure it's not perfect, especially since you think it's not working, but there was a lot of work done to validate default values.  I'm rewriting it anyways to use JSON Schema validation so I don't have to reinvent the wheel like we did earlier in swagger-tools life.

**Comment by IvanGoncharov** [comment]
@whitlockjc I think, this conversation moving from JSON Schema into Swagger area.
So I create `swagger-tool` issue, let's continue discussion over there.
