### ISSUE TITLE
async custom format validator does not return correct path

### ISSUE THREAD

**Issue by sylar107** [zaggino/z-schema#209]
Problem: Custom async format validator does not return correct path, for example it returns "#/" instead of "#/something".

Sample test:
```
"use strict";

module.exports = {
  description: "async validator returns wrong path",
  async: true,
  options: {
    asyncTimeout: 2000
  },
  setup: function(validator, Class) {
    // asynchronous validator
    Class.registerFormat("string-length", function(str, callback) {
      setTimeout(function() {
        callback(str.length > 10);
      }, 1);
    });

    // same as above but synchronous (comment out the validator above and try with this instead)
    // Class.registerFormat("string-length", function(str) {
    //   return str.length > 10;
    // });
  },
  schema: {
    description: "Some schema",
    type: "object",
    properties: {
      userId: {
        type: "string",
        format: "string-length"
      }
    },
    required: ["userId"]
  },
  tests: [
    {
      description: "Wrong path in custom format async validator",
      data: { userId: "1" },
      valid: false,
      after: function(err) {
        expect(err[0].path).toEqual("#/userId");
      }
    }
  ]
};

```

**Comment by kallaspriit** [comment]
Same issue here, makes it very hard to show the user where the mistakes filling out a form were made.

**Comment by kallaspriit** [comment]
@zaggino could You please verify the fix and merge it :)

**Comment by zaggino** [comment]
Fixed by https://github.com/zaggino/z-schema/pull/228
Thanks @kallaspriit

**Comment by kallaspriit** [comment]
I updated the library in my project and I'm afraid that simply removing the problematic line is not a solution after all because it fails if there are more than one properties in an object schema. Unfortunately this was not covered by any of the tests.

Here's an updated test case that fails:

*test/ZSchemaTestSuite/Issue209.js*
```javascript
"use strict";

const testAsync = true;

module.exports = {
  description: "Issue #209 - async validator returns wrong path",
  async: true,
  options: {
    asyncTimeout: 2000
  },
  setup: function(validator, Class) {
    if (testAsync) {
      // asynchronous validator
      Class.registerFormat("string-length", function(str, callback) {
        setTimeout(function() {
          callback(str.length > 10);
        }, 1);
      });
    } else {
      // same as above but synchronous (comment out the validator above and try with this instead)
      Class.registerFormat("string-length", function(str) {
        return str.length > 10;
      });
    }
  },
  schema: {
    description: "Some schema",
    type: "object",
    properties: {
      projectId: {
        type: "number"
      },
      userId: {
        type: "string",
        format: "string-length"
      }
    }
  },
  tests: [
    {
      description: "Wrong path in custom format async validator",
      data: { projectId: 1, userId: "1" },
      valid: false,
      after: function(err) {
        expect(err[0].path).toEqual("#/userId");
      }
    }
  ]
};
```

Fails with `Expected '#/userId/projectId' to equal '#/userId'.`.

The additional property `projectId` remains in the path. The `.pop()` removes it but being sync, it also removes the `userId`.

I guess the solution would be to make the `exports.validate.call(this, report, s[idx2], propertyValue);` properly async (or accept a callback) and wait for it to complete before performing the `report.path.pop();` but this seems to be fairly complicated given the current architecture. It would probably be much easier for the author of the library.

@zaggino You should probably roll back the improper fix. Sorry for the false hope, should have checked it with my project first. Also would You be willing to tackle this problem yourself?
