### ISSUE TITLE
Versions mismatch cause npm error

### ISSUE THREAD

**Issue by YonatanKra** [zaggino/z-schema#243]
Hi,
We have a dependency with `z-schema: ^3.17.0`.
On the release part I see there's a version 2.26.0 - https://github.com/zaggino/z-schema/releases/tag/v3.26.0. 
On npm this version does not exist (last version is 2.25.1):
![image](https://user-images.githubusercontent.com/6459899/60971101-18b64e00-a32c-11e9-9468-64f3fec670bf.png)

The problem is - `npm install` looks for 2.26.0.
I there a reason why 2.26.0 appears to be the last version but it doesn't exist on NPM?

**Comment by zaggino** [comment]
Hi, unless you're using Node 4.x, you can safely update to z-schema 4.x

**Comment by smartmouse** [comment]
HI , we ran into the same issue, We cannot upgrade since we have shirnkwrap already/ Is it possible to publish that version.
Appreciated your help.

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for z-schema@3.26.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by rmg** [comment]
As far as I can tell, `3.26.0` was unpublished.

Since `3.26.0` was already published once there is no way to re-publish it. The best that could be done is to branch from the `3.26.0` tag and re-publish as `3.26.1`.

The problem @smartmouse is reporting is an unfortunate case of generating an `npm-shrinkwrap.json` between when `3.26.0` was published and when it was unpublished. The use of a private (caching) registry means the unpublish wasn't noticed. In fact, the `z-schema-2.26.0.tgz` tarball probably still exists on many such registries :-(

Since 3.26.0 exists in caches, I took a quick look at it. I couldn't find any obvious reason to unpublish it (eg. leaked personal information) so I'm guessing it was retracted in favour of just jumping to 4.x. I'm sure @zaggino had no idea that anyone would have installed and pinned to that specific version within the 72 hours (max) that the version existed on npm.

**Comment by zaggino** [comment]
`3.26.0` was published and it broke node v4, by mistake, to not introduce any code-breaks with semver-minor, I've unpublished it

I've also decided to go with `4.0.0` because I don't see a reason to keep supporting so old node versions
