### ISSUE TITLE
`lastReport` absent in `index.d.ts`

### ISSUE THREAD

**Issue by tkf144** [zaggino/z-schema#279]
Hi. Is it deliberate that the report of the last validation is not included in the typings (i.e. `index.d.ts`)? I have come across this library through another, and it makes use of `Validator.lastReport`, however on converting the library to Typescript, `tsc` complains that `lastReport` does not exist there when I seem to have no trouble making use of it anyway.

Cheers

**Comment by zaggino** [comment]
Hey, I the typings are not generated automatically for this project, because it's in JS not TS originally. 
I've pushed https://github.com/zaggino/z-schema/commit/7d7ecfb464759b392d6a5db9a17cdbe24bd084b4
But if that's not enough, feel free to open a PR with an update to https://github.com/zaggino/z-schema/blob/master/index.d.ts

**Comment by tkf144** [comment]
Understood. Thanks for the fix @zaggino.
